### ISSUE TITLE
do you think TarsosDSP could be used to create a car horn detector??

### ISSUE THREAD

**Issue by cellurl3** [Scoutdrago3/MusicToGraph#2]
I can't figure out who wrote TarsosDSP library?

But thanks for the explaination.
https://devpost.com/software/music-to-graph-b8da6o

Does it just run an FFT over and over? 
Does the word pitch really mean strongest-frequency-value?  
I don't see it on Google Play store.

Any dialog appreciated!

Jim Pruett
Sorry to ask questions as an issue......

**Comment by saidkharboutli** [comment]
To be quite honest I was very surprised to find a comment on this very old project. TarsosDSP can be found on GitHub at: https://github.com/JorenSix/TarsosDSP. The creator also generated some documentation you can find here: https://0110.be/releases/TarsosDSP/TarsosDSP-latest/TarsosDSP-latest-Documentation/. It may be better to direct your questions to JorenSix, however I can touch on them.

Regarding FFT: we did not implement the audio processing (and thus, we did not employ FFT or related algorithms), however, looking at the TarsosDSP GitHub, it seems they used an algorithm other than FFT to process the audio signal.

Regarding pitch: not entirely confident, but if I had to guess, it is more likely to be the latter. That is the case in our usage of the TarsosDSP, at least.

Regarding Play Store: this app was created at a hackathon and to be honest we haven't done much else with it since then. I don't think I have plans to port it over to an Android app either.

Hope I helped, stay safe.

**Comment by cellurl3** [comment]
thanks itsyeed.

Car horns do create a pitch response in TarsosDSP, so I think I will just look for 10 idential subsequent pitches show up in the range of car horns... .  (my winter project)

Thanks again for the dialog.!
